### ISSUE TITLE
Random spawn on death?

### ISSUE THREAD

**Issue by ciduxhd** [tiagocli/EasySetSpawn#8]
Hello I have tried using multiple different spawn plugins and this is the one I decided to choose to stick with expect the Issue I am having with all but one is that when you die in game it will spawn you near spawn it doesn't spawn you on the block set as spawn just around it. I am using minecraft version 1.16.1 with a few other plugins installed even though the issue persisted when I used just the plugin by itself with nothing else.

**Comment by tiagocli** [comment]
Have you enabled (set to true) the following option in the config.yml: https://github.com/tiagocli/EasySetSpawn/blob/488f8235dee6a4be9d2d7037a6a43a386472b515/src/config.yml#L4 ?

**Comment by tiagocli** [comment]
Closed for inactivity
